/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MeRouteImport } from './routes/me'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitingIndexRouteImport } from './routes/waiting.index'
import { Route as WaitingStoreIdRouteImport } from './routes/waiting.$storeId'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as ApiPublicPosTableStatusRouteImport } from './routes/api/public/pos/table-status'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingIndexRoute = WaitingIndexRouteImport.update({
  id: '/waiting/',
  path: '/waiting/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingStoreIdRoute = WaitingStoreIdRouteImport.update({
  id: '/waiting/$storeId',
  path: '/waiting/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosTableStatusRoute = ApiPublicPosTableStatusRouteImport.update({
  id: '/api/public/pos/table-status',
  path: '/api/public/pos/table-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/waiting/$storeId': typeof WaitingStoreIdRoute
  '/waiting/': typeof WaitingIndexRoute
  '/api/public/pos/table-status': typeof ApiPublicPosTableStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/waiting/$storeId': typeof WaitingStoreIdRoute
  '/waiting': typeof WaitingIndexRoute
  '/api/public/pos/table-status': typeof ApiPublicPosTableStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/me': typeof MeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/waiting/$storeId': typeof WaitingStoreIdRoute
  '/waiting/': typeof WaitingIndexRoute
  '/api/public/pos/table-status': typeof ApiPublicPosTableStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/me'
    | '/sitemap.xml'
    | '/store/$storeId'
    | '/waiting/$storeId'
    | '/waiting/'
    | '/api/public/pos/table-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/me'
    | '/sitemap.xml'
    | '/store/$storeId'
    | '/waiting/$storeId'
    | '/waiting'
    | '/api/public/pos/table-status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/me'
    | '/sitemap.xml'
    | '/store/$storeId'
    | '/waiting/$storeId'
    | '/waiting/'
    | '/api/public/pos/table-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  MeRoute: typeof MeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
  WaitingStoreIdRoute: typeof WaitingStoreIdRoute
  WaitingIndexRoute: typeof WaitingIndexRoute
  ApiPublicPosTableStatusRoute: typeof ApiPublicPosTableStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting/': {
      id: '/waiting/'
      path: '/waiting'
      fullPath: '/waiting/'
      preLoaderRoute: typeof WaitingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting/$storeId': {
      id: '/waiting/$storeId'
      path: '/waiting/$storeId'
      fullPath: '/waiting/$storeId'
      preLoaderRoute: typeof WaitingStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos/table-status': {
      id: '/api/public/pos/table-status'
      path: '/api/public/pos/table-status'
      fullPath: '/api/public/pos/table-status'
      preLoaderRoute: typeof ApiPublicPosTableStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  MeRoute: MeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
  WaitingStoreIdRoute: WaitingStoreIdRoute,
  WaitingIndexRoute: WaitingIndexRoute,
  ApiPublicPosTableStatusRoute: ApiPublicPosTableStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
